version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 25
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Toronto"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"

  - package-ecosystem: 'pip'
    directory: "/"
    open-pull-requests-limit: 25
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Toronto"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 25
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Toronto"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
